import Head from 'next/head'
// import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import  Link from 'next/link'
import React from "react";
import Dummy from "./components/Dummy";
export default function Home() {
  return (
    <div className={styles.container}>
        {/*<Dummy/>*/}

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/*<Script src='/script.js' strategy='lazyOnload'></Script>*/}
        <style jsx>
            {`
              .myclass {
                color: red;
              }
            `}
        </style>
        <main className={styles.main}>
            <h1 className={styles.heading}><span className='myclass dummy'>Blog Page</span></h1>
            <div className={styles.imagefile}>
                {/*<Image className={styles.img} layout='fill' src='https://images.pexels.com/photos/1767434/pexels-photo-1767434.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500' alt='imges' />*/}
                {/* <Image className={styles.img} src='/img.webp' width={237} height={160}/>*/}
                <img className={styles.img} src='/img.webp' width={237} height={160} alt='blog page'/>

            </div>
            <div className={styles.blog}>
            <div className={styles.blogItem}>
                <h3>How to learn Javascript by Nextjs</h3>
                <p>Javascript is scripting and programming lunguage.</p>
            </div>
            <div className={styles.blogItem}>
                <h3>How to learn Javascript by Nextjs</h3>
                <p>Javascript is scripting and programming lunguage.</p>
            </div>
            <div className={styles.blogItem}>
                <h3>How to learn Javascript by Nextjs</h3>
                <p>Javascript is scripting and programming lunguage.</p>
            </div>
            </div>
        </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
